codecov:
  require_ci_to_pass: true
  branch: master
  max_report_age: false

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        if_not_found: success
        only_pulls: true

ignore:
  - "^/tests/**/*" # ignore test harness code

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false
